alias: ASSIST - Mic Switches
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.firehd_7_stt
    to: start
    id: LR Mic On
  - platform: state
    entity_id:
      - sensor.firehd_7_stt
    id: LR Mic Off
    to: end
  - platform: state
    entity_id:
      - sensor.firehd_7_stt
    id: LR Mic Off
    to: no-text-recognized
  - platform: state
    entity_id:
      - switch.firehd_7_mic
    to: "off"
    id: micofftoon
    enabled: false
  - platform: template
    value_template: "\"{% if not is_state('switch.firehd_7_mic', 'on') %}true{% endif %}\""
    id: micautoon
    enabled: false
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - LR Mic On
        sequence:
          - service: input_boolean.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: input_boolean.lr_tablet_mic
      - conditions:
          - condition: trigger
            id:
              - LR Mic Off
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id:
                - input_boolean.lr_tablet_mic
            data: {}
      - conditions:
          - condition: trigger
            id:
              - micofftoon
        sequence:
          - service: homeassistant.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: switch.firehd_7_mic
mode: single
