alias: ASSIST - Control display TabletMaster
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.tabletmaster_browser_path
    id: ModeControl_TabletMaster
    enabled: true
  - platform: state
    entity_id:
      - sensor.assistsat_viewmaster
    id: ModeControl_TabletMaster
    attribute: mode
    enabled: true
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - ModeControl_TabletMaster
        sequence:
          - if:
              - condition: state
                entity_id: sensor.assistsat_viewmaster
                state: normal
                attribute: mode
                enabled: true
            then:
              - delay:
                  seconds: >-
                    {{states.sensor.assistsat_viewmaster.attributes.view_timeout}}
              - service: browser_mod.navigate
                metadata: {}
                data:
                  path: /dashboard-viewassist/clock
                target:
                  device_id: "{{ device_id('sensor.tabletmaster_browser_path') }}"
          - if:
              - condition: state
                entity_id: sensor.assistsat_viewmaster
                state: music
                attribute: mode
            then:
              - delay:
                  seconds: >-
                    {{states.sensor.assistsat_viewmaster.attributes.view_timeout}}
              - service: browser_mod.navigate
                metadata: {}
                data:
                  path: /dashboard-viewassist/music
                target:
                  device_id: "{{ device_id('sensor.tabletmaster_browser_path') }}"
          - if:
              - condition: state
                entity_id: sensor.assistsat_viewmaster
                state: cycle
                attribute: mode
            then:
              - repeat:
                  while:
                    - condition: state
                      entity_id: sensor.assistsat_viewmaster
                      state: cycle
                      attribute: mode
                  sequence:
                    - repeat:
                        for_each: >-
                          {{ state_attr ('sensor.assistsat_viewmaster',
                          'cycle_view')}}
                        sequence:
                          - service: browser_mod.navigate
                            data:
                              path: /dashboard-viewassist/{{repeat.item}}
                            target:
                              device_id: >-
                                {{ device_id('sensor.tabletmaster_browser_path')
                                }}
                            enabled: false
                          - if:
                              - condition: state
                                entity_id: sensor.assistsat_viewmaster
                                state: cycle
                                attribute: mode
                            then:
                              - service: browser_mod.navigate
                                data:
                                  path: /dashboard-viewassist/{{repeat.item}}
                                target:
                                  device_id: >-
                                    {{
                                    device_id('sensor.tabletmaster_browser_path')
                                    }}
                              - delay:
                                  seconds: >-
                                    {{ state_attr
                                    ('sensor.assistsat_viewmaster',
                                    'view_timeout')}}
                                enabled: true
                          - if:
                              - condition: state
                                entity_id: sensor.assistsat_viewmaster
                                state: cycle
                                attribute: mode
                            then:
                              - delay:
                                  seconds: >-
                                    {{ state_attr
                                    ('sensor.assistsat_viewmaster',
                                    'view_timeout')}}
                            enabled: false
          - service: browser_mod.navigate
            metadata: {}
            data:
              path: /dashboard-viewassist/clock
            target:
              device_id: "{{ device_id('sensor.tabletmaster_browser_path') }}"
            enabled: false
mode: single
