alias: ASSIST - Sentences demo
description: ""
trigger:
  - platform: conversation
    command: washer demo
    id: washerdemo
  - platform: conversation
    command:
      - doorbell demo
    id: doorbelldemo
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - washerdemo
        sequence:
          - service: input_boolean.turn_on
            metadata: {}
            data: {}
            target:
              entity_id:
                - input_boolean.washer
                - input_boolean.demo_washer
          - set_conversation_response: ""
      - conditions:
          - condition: trigger
            id:
              - doorbelldemo
        sequence:
          - service: browser_mod.navigate
            metadata: {}
            data:
              path: /dashboard-viewassist/doorbellcamera
            target:
              device_id: "{{ states('input_text.assist_display_entity')}}"
mode: single
