alias: View Assist - Search Wikipedia
description: ""
trigger:
  - platform: conversation
    command:
      - who is {name}
      - what is [the] [a] [an] {name}
condition: []
action:
  - variables:
      target_satellite_device: |-
        {% for sat in expand('group.viewassist_satellites') %}
          {% if device_id(sat.attributes.mic_device)  == trigger.device_id %}
            {{ sat.entity_id }}
          {% endif %}
        {% endfor %}
      target_display_device: "{{ device_id(state_attr(target_satellite_device, 'display_device')) }}"
      target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device') }}"
    enabled: true
  - service: rest_command.wiki_how
    response_variable: wiki_response
    enabled: true
    data:
      name: "{{ trigger.slots.name  |regex_replace(find=' ', replace='_') }}"
  - service: python_script.set_state
    data:
      entity_id: "{{ target_satellite_device }}"
      title: Wikipedia Search
  - service: python_script.set_state
    data:
      entity_id: "{{ target_satellite_device }}"
      message: "{{ wiki_response['content']['extract'] }}"
  - service: python_script.set_state
    data:
      entity_id: "{{ target_satellite_device }}"
      image: "{{ wiki_response['content']['thumbnail']['source'] }}"
    enabled: true
  - service: python_script.set_state
    data:
      entity_id: "{{ target_satellite_device }}"
      message_font_size: 3vw
  - set_conversation_response: Here's what I found on wikipedia
    enabled: true
  - service: browser_mod.navigate
    data:
      path: /dashboard-viewassist/infopic
    target:
      device_id: "{{target_display_device}}"
mode: single
