alias: ASSIST - Control Display OLD
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.tabletfullkiosk_browser_path
    id: ModeControl_Tabletfullkiosk
  - platform: state
    entity_id:
      - sensor.thinksmart_lr_browser_path
    id: ModeControl_Thinksmart-LR
  - platform: state
    entity_id:
      - switch.lr_and_mbr_lights
    from: "on"
    to: "off"
    id: LightsOff
  - platform: state
    entity_id:
      - switch.lr_and_mbr_lights
    from: "off"
    to: "on"
    id: LightsOn
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - ModeControl_Tabletfullkiosk
        sequence:
          - delay:
              seconds: "{{states.sensor.assistsat_viewlr.attributes.view_timeout}}"
          - if:
              - condition: state
                entity_id: sensor.assistsat_viewlr
                state: normal
                attribute: mode
            then:
              - service: browser_mod.navigate
                metadata: {}
                data:
                  path: /dashboard-tablet/clock
                target:
                  device_id: "{{ device_id('sensor.tabletfullkiosk_browser_path') }}"
          - if:
              - condition: state
                entity_id: sensor.assistsat_viewlr
                state: music
                attribute: mode
            then:
              - service: browser_mod.navigate
                metadata: {}
                data:
                  path: /dashboard-tablet/music
                target:
                  device_id: "{{ device_id('sensor.tabletfullkiosk_browser_path') }}"
      - conditions:
          - condition: trigger
            id:
              - ModeControl_Thinksmart-LR
        sequence:
          - delay:
              seconds: >-
                {{states.sensor.assistsat_viewlrthinksmart.attributes.view_timeout}}
          - if:
              - condition: state
                entity_id: sensor.assistsat_viewlrthinksmart
                state: normal
                attribute: mode
            then:
              - service: browser_mod.navigate
                metadata: {}
                data:
                  path: /dashboard-tablet/clock
                target:
                  device_id: "{{ device_id('sensor.thinksmart_lr_browser_path') }}"
          - if:
              - condition: state
                entity_id: sensor.assistsat_viewlrthinksmart
                state: music
                attribute: mode
            then:
              - service: browser_mod.navigate
                metadata: {}
                data:
                  path: /dashboard-tablet/music
                target:
                  device_id: "{{ device_id('sensor.thinksmart_lr_browser_path') }}"
      - conditions:
          - condition: trigger
            id:
              - LightsOff
        sequence:
          - service: light.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: light.tabletfullkiosk_screen
      - conditions:
          - condition: trigger
            id:
              - LightsOn
        sequence:
          - service: light.turn_on
            target:
              entity_id:
                - light.tabletfullkiosk_screen
            data: {}
mode: single
