alias: ASSIST - Control display Thinksmart Newest
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.thinksmart_lr_browser_path
    id: ModeControl_Thinksmart-LR
  - platform: state
    entity_id:
      - sensor.assistsat_viewlrthinksmart
    id: ModeControl_Thinksmart-LR
    attribute: mode
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.thinksmart_lr
    id: timerend
  - platform: state
    entity_id:
      - sensor.assistsat_viewlrthinksmart
    id: Cycle_Thinksmart-LR
    attribute: mode
    to: cycle
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - ModeControl_Thinksmart-LR
        sequence:
          - service: timer.start
            metadata: {}
            data:
              duration: >-
                {{states.sensor.assistsat_viewlrthinksmart.attributes.view_timeout}}
            target:
              entity_id: timer.thinksmart_lr
      - conditions:
          - condition: trigger
            id:
              - timerend
        sequence:
          - if:
              - condition: state
                entity_id: sensor.assistsat_viewlrthinksmart
                state: normal
                attribute: mode
                enabled: true
            then:
              - service: browser_mod.navigate
                metadata: {}
                data:
                  path: /dashboard-viewassist/clock
                target:
                  device_id: "{{ device_id('sensor.thinksmart_lr_browser_path') }}"
          - if:
              - condition: state
                entity_id: sensor.assistsat_viewlrthinksmart
                state: music
                attribute: mode
                enabled: true
            then:
              - service: browser_mod.navigate
                metadata: {}
                data:
                  path: /dashboard-viewassist/music
                target:
                  device_id: "{{ device_id('sensor.thinksmart_lr_browser_path') }}"
      - conditions:
          - condition: trigger
            id:
              - Cycle_Thinksmart-LR
        sequence:
          - repeat:
              while:
                - condition: state
                  entity_id: sensor.assistsat_viewlrthinksmart
                  state: cycle
                  attribute: mode
              sequence:
                - repeat:
                    for_each: >-
                      {{ state_attr ('sensor.assistsat_viewlrthinksmart',
                      'cycle_view')}}
                    sequence:
                      - if:
                          - condition: state
                            entity_id: sensor.assistsat_viewlrthinksmart
                            state: cycle
                            attribute: mode
                        then:
                          - service: browser_mod.navigate
                            data:
                              path: /dashboard-viewassist/{{repeat.item}}
                            target:
                              device_id: >-
                                {{
                                device_id('sensor.thinksmart_lr_browser_path')
                                }}
                      - if:
                          - condition: state
                            entity_id: sensor.assistsat_viewlrthinksmart
                            state: cycle
                            attribute: mode
                        then:
                          - wait_for_trigger:
                              platform: event
                              event_type: timer.finished
                              event_data:
                                entity_id: timer.thinksmart_lr
mode: parallel
