alias: VIEW ASSIST - Day Date Day of Week
description: ""
trigger:
  - platform: conversation
    command:
      - What is the date
      - what day is it
      - what is today
    id: date
  - platform: conversation
    command:
      - What day of the week is it
      - "[What('s)] [is] [the] day of the week [is it]"
    id: dayofweek
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - date
        sequence:
          - set_conversation_response: Today is {{ now().strftime("%A %B %-d")}}
          - variables:
              target_satellite_device: |-
                {% for sat in expand('group.viewassist_satellites') %}
                  {% if device_id(sat.attributes.mic_device)  == trigger.device_id %}
                    {{ sat.entity_id }}
                  {% endif %}
                {% endfor %}
              target_display_device: >-
                {{ device_id(state_attr(target_satellite_device,
                'display_device')) }}
              target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device') }}"
            enabled: true
          - service: browser_mod.navigate
            metadata: {}
            data:
              path: /dashboard-viewassist/clock
            target:
              device_id: "{{ target_display_device }}"
      - conditions:
          - condition: trigger
            id:
              - dayofweek
        sequence:
          - set_conversation_response: Today is {{ now().strftime("%A")}}
          - variables:
              target_satellite_device: |-
                {% for sat in expand('group.viewassist_satellites') %}
                  {% if device_id(sat.attributes.mic_device)  == trigger.device_id %}
                    {{ sat.entity_id }}
                  {% endif %}
                {% endfor %}
              target_display_device: >-
                {{ device_id(state_attr(target_satellite_device,
                'display_device')) }}
              target_mediaplayer_device: "{{ state_attr(target_satellite_device, 'mediaplayer_device') }}"
            enabled: true
          - service: browser_mod.navigate
            metadata: {}
            data:
              path: /dashboard-viewassist/clock
            target:
              device_id: "{{ target_display_device }}"
mode: single
