blueprint:
  name: View Assist - Control display template
  description: This is used as a base for setting up display control on a View Assist Satellite
  domain: automation
  input:
    satellite:
      name: Satellite
      description: The View Assist device entity to control
      default: "sensor.viewassist-living_room"
    timer:
      name: Timer
      description: The associated timer device entity for the satellite
      default: "timer.viewassist-living_room"
    dashboard:
      name: Dashboard
      description: The base dashboard for View Assist
      default: "/dashboard-viewassist/"
    display:
      name: Display Device
      description: The browsermod display device used by View Assist
      default: "sensor.browsermod-livingroom_browser_path"    
trigger:
  - platform: state
    entity_id:
      - !input display
    id: ModeControl
  - platform: state
    entity_id:
      - !input satellite
    id: ModeControl
    attribute: mode
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: !input timer
    id: timerend
  - platform: state
    entity_id:
      - !input satellite
    id: Cycle
    attribute: mode
    to: cycle
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - ModeControl
        sequence:
          - service: timer.start
            data:
              duration: >-
                {{states[satellite].attributes.view_timeout}}
            target:
              entity_id: !input timer
      - conditions:
          - condition: trigger
            id:
              - timerend
        sequence:
          - if:
              - condition: state
                entity_id: !input satellite
                state: normal
                attribute: mode
                enabled: true
            then:
              - service: browser_mod.navigate
                data:
                  path: "{{dashboard}}/clock"
                target:
                  device_id: "{{device_id(states[satellite].attributes.display_device)}}"
          - if:
              - condition: state
                entity_id: !input satellite
                state: music
                attribute: mode
                enabled: true
            then:
              - service: browser_mod.navigate
                data:
                  path: "{{dashboard}}/music"
                target:
                  device_id: "{{device_id(states[satellite].attributes.display_device)}}"
      - conditions:
          - condition: trigger
            id:
              - Cycle
        sequence:
          - repeat:
              while:
                - condition: state
                  entity_id: !input satellite
                  state: cycle
                  attribute: mode
              sequence:
                - repeat:
                    for_each: >-
                      {{ state_attr (satellite,'cycle_view')}}
                    sequence:
                      - if:
                          - condition: state
                            entity_id: !input satellite
                            state: cycle
                            attribute: mode
                        then:
                          - service: browser_mod.navigate
                            data:
                              path: "{{dashboard}}/{{repeat.item}}"
                            target:
                              device_id: "{{device_id(states[satellite].attributes.display_device)}}"
                      - if:
                          - condition: state
                            entity_id: !input satellite
                            state: cycle
                            attribute: mode
                        then:
                          - wait_for_trigger:
                              platform: event
                              event_type: timer.finished
                              event_data:
                                entity_id: !input timer
mode: parallel
