alias: ASSIST - Wikipedia Search
description: ""
trigger:
  - platform: conversation
    command:
      - who is {name}
      - what is [the] [a] [an] {name}
    id: who
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - who
        sequence:
          - service: rest_command.wiki_how
            response_variable: wiki_response
            enabled: true
            data:
              name: "{{ trigger.slots.name  |regex_replace(find=' ', replace='_') }}"
          - service: python_script.set_state
            data:
              entity_id: sensor.assistsat_viewlr
              title: Wikipedia Search
          - service: python_script.set_state
            data:
              entity_id: sensor.assistsat_viewlr
              message: "{{ wiki_response['content']['extract'] }}"
          - service: python_script.set_state
            data:
              entity_id: sensor.assistsat_viewlr
              image: "{{ wiki_response['content']['thumbnail']['source'] }}"
            enabled: true
          - service: python_script.set_state
            data:
              entity_id: sensor.assistsat_viewlr
              message_font_size: 2vw
          - set_conversation_response: Here's what I found on wikipedia
            enabled: true
          - service: browser_mod.navigate
            data:
              path: /dashboard-tablet/infopic
            target:
              entity_id: sensor.tabletfullkiosk_browser_path

